README.md
lib/error/errors.js
lib/fotingo-review.js
lib/git/github/index.js
lib/util.js
package.json
src/error/errors.js
src/fotingo-review.js
src/git/github/index.js
src/util.js
yarn.lock

* feat(review): allow to add labels to PRs
* Update github to latest version.
* Refactor github calls to match the new data structure.
* Add labels to PR after it's been created.
* Check that labels match the existing ones.
* fix(error): show message when there is no stack
Fixes #5.

Allow to add labels to PRs

---

lib/fotingo-review.js
lib/fotingo-start.js
lib/git/local/index.js
lib/reporter/index.js
src/fotingo-review.js
src/fotingo-start.js
src/git/local/index.js
src/reporter/index.js

fix(ui): show issues and branch names in ui

---

src/fotingo-review.js
src/git/local/index.js

* fix(git): read remote and branch from config when getting history
* origin/master value was hardcoded.
Fixes #20.

Hardcoded branch name in getBranchInfo

---

src/git/local/index.js

* Raw property can contain rubbish.
* Use prefix + issue.
Fixes #15.

fix(git): parse issues correctly

---

src/fotingo-review.js
src/git/github/index.js

* Still keep the issue ids but do not link to issue tracker.

* fix(Github): do not add links to issues if mode is simple

---

src/issue-tracker/jira/status.js

* Use a set of regex to identify transition ids.
* Fallback to question if can't find any of the ids.
* Improve UI test so users can understand what is being asked better.
Fixes #11.

fix(Jira): improve transition setup

---

package.json
src/error/errors.js
src/git/local/index.js
src/git/util.js

* fix(Review): show error message when no issue in branch
* chore(scripts): build before release
Fixes #16.

Show better error when there is no issue on the branch name

---

src/git/local/index.js

Read errno and add switch with NodeGit.Error.CODE.
Fixes #3.

chore(Git): add ability to differentiate among different errors

---

src/fotingo-start.js

* If this option is passed, just set the issue in progress, but do not
create a new branch.
Fixes #18.

feat(Start): add -n option

---

package.json
src/fotingo-review.js
src/git/github/index.js
yarn.lock

* bump github version
* feat(review): allow to add reviewers to the PR
Option -r.
Fixes #4.

review_request

---

src/config/index.js
src/error/errors.js
src/fotingo-review.js
src/fotingo-start.js
src/git/local/index.js

* Add -b option to set the new branch in both `start` and `review`.
* Add support for in memory config. This never gets dumped to the config file. This will allow to add more features like this.
* Refactor error handling in git. It is all in one function now.
Fixes #34.

feat: allow to overwrite base branch

---

src/error/errors.js
src/issue-tracker/jira/index.js

Instead of the HTML response from Jira.
Fixes #42.

fix(jira): show error when login fails in second attempt

---

README.md

docs(readme): indicate the permissions the github token needs

---

src/fotingo-review.js
src/git/local/index.js
src/git/util.js

feat(git): extract branch name according to branch template

---

package.json
src/error/errors.js
src/fotingo-review.js
src/git/github/index.js
src/init.js
src/issue-tracker/http-client.js
src/issue-tracker/jira/status.js
yarn.lock

Reformat all the code with the new perttier version.

chore: update prettier and eslint to latest version

---

package.json
test/.eslintrc
test/error/index.test.js
yarn.lock

Hopefully this is the beginning towards a better (or exisitng) test coverage.
* chore: add jest
* test(error): add tests for error module

test(error): add tests for error module

---

src/error/errors.js
src/fotingo-release.js

fix(release): check that a release name is passed

---

package.json
src/git/Git.ts
yarn.lock

This PR updates some dependencies to the latest version
**Changes**
* chore(dependencies): bump request
* chore(Git): avoid name shadowing
* chore(dependencies): update standard-version

chore: update some dependencies

---

package.json
src/git/Git.ts
yarn.lock

Update some more dependencies
**Changes**
* chore(dependencies): ensure minimum version of lodash
* chore(dependencies): ensure minimum version of sql
* fix(Git): add missing types

chore: update more dependencies

---

src/io/input-util.ts
src/io/text-util.ts

fix(InputUtil): throw an error when the list of matches is empty

---

src/enhanceConfig.ts
src/git/Git.ts
src/git/GitError.ts
src/ui/errorCodeToMessage.ts
src/ui/useCmd.ts

The config enhancer was assuming that there is a git repo and was not catching exceptions correctly
**Changes**
* fix(config): do not enhance config when not in a git repository
* fix: do not crash when run outside of a git repo

fix: don't crash when run outside of a git repo

---

src/commands/run.ts
src/ui/Fotingo.tsx
src/ui/Messages.tsx
src/ui/props.ts

Make all of the messages static when trhe DEBUG env varialbe is set
**Changes**
* chore(run): pass debugging flag to UI
* feat(Messages): always log messages as static in debug mode

feat: make UI friendly when DEBUG is set

---

src/issue-tracker/jira/Jira.ts

It was broke after the issue shape refactor
**Changes**
* fix(Jira): access project id correctly

fix(Jira): access project id correctly

---

.github/workflows/main-workflow.yml
jest.config.js

Setup coveralls in the main workflow
**Changes**
* chore(jest): generate coverage report in lcov too
* chore(workflows): setup coveralls

chore: setup code coverage

---

src/cli/review.ts
src/cli/start.ts

It overrides the user config
**Changes**
* fix: do not default -b option

fix: do not default -b option

---

src/commands/Start.ts

When adding eslint, I removed some code that shouldn't have been deleted
**Changes**
* fix(Start): add removed code that shouldn't have been deleted

fix(Start): branch is not getting created

---

src/commands/util.ts

Sometimes the commit message will contain referecnes to other things
such as github issues or any other link. There is some logic to check if
those items are jira tickets, but the check if very simple, so ignoring
the 404s works better.
**Changes**
* fix(Review): ignore 404 for tickets found in the commit messages

fix(Review): ignore 404 for tickets found in the commit messages

---

.github/workflows/auto-merge-prs.yml

Those labeled with the automerge tag. The goal is to automate merging dependabot PRs that pass all the checks.
**Changes**
* chore(github): create action to automerge prs

chore(github): create action to automerge prs

---

src/git/Github.ts

The data was mixed
**Changes**
* fix(github): pass description and summary correctly

fix(github): pass description and summary correctly

---

src/git/Github.ts

I should have tests for this...
**Changes**
* fix(Github): fix summary and description for Jira tickets

fix(Github): fix summary and description for Jira tickets

---

.commitlintrc.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.releaserc.json
README.md
package.json
yarn.lock

**Changes**
* chore: setup commit msg hook
* chore: automate release process
* chore: remove beta from package.json

chore: add commitlint and semantic releae

---

.github/workflows/auto-merge-prs.yml

chore(actions): update automerge

---

.github/workflows/auto-merge-prs.yml

chore(actions): do not delete automerge tag

---

README.md

v2.x.x is no longer in beta
**Changes**
* docs(readme): remove beta

docs(readme): remove beta

---

src/git/Github.ts

* chore(github): increases pr title length
- This should avoid trimming most of our PR titles from Jira tickets

chore(github): increases pr title length

---

src/cli/FotingoCommand.ts

The current setup doesn't allow to use a different default branch by just updating the config file
**Changes**
* fix: use actual cmd flags for runtime default branch

fix: use actual cmd flags for runtime default branch

---

src/git/Git.ts
src/git/GitError.ts
src/issue-tracker/jira/Jira.ts
src/ui/errorCodeToMessage.ts
test/git/Git.test.ts

This PR improves error handling for different issues
**Changes**
* chore(git): improve no remote error
* fix(git): improve error message when push fails
* fix(jira): show better error message when Jira returns a 401

fix: improve several errors

---

src/config.ts
test/config.test.ts
test/lib/data.ts

Allow to override some configurations with env variables
**Changes**
* feat(config): allow to override config via env variables

feat(config): allow to override config via env variables

---

src/commands/verify.ts
src/git/Github.ts
src/types.ts
test/issue-tracker/__snapshots__/Jira.test.ts.snap
test/lib/data.ts

Add a verify command. Used to verify connection to remote services
**Changes**
* feat: add verify cmd

feat: add verify cmd

---

package.json
yarn.lock

We're running into issues within a Docker node 16.14.2 image when running `fotingo release`
**Changes**
* fix: bumps sqlite3 to fix error w node 16.14

fix: bumps sqlite3 to fix error w node 16.14

---

src/git/Branch.ts
src/templates/getReleaseNotes.ts
src/types.ts

| Before | After |
| --- | --- |
| <img width="570" alt="Screenshot 2023-04-20 at 2 33 20 PM" src="https://user-images.githubusercontent.com/51345108/233383385-97ef1817-bcf3-4d33-b327-905e8bdf3c06.png"> | <img width="570" alt="Screenshot 2023-04-20 at 2 35 24 PM" src="https://user-images.githubusercontent.com/51345108/233383442-99bc2adc-e3bb-45c5-82db-1f3a21d86aee.png"> |
**Changes**
* feat: add new issue type: Tech-debt

feat: add new issue type: Tech-debt
