src/error/errors.js, src/error/index.js, src/git/github/index.js
Error handling can be done better, but the typical error would be duplicated PR.
Fotingo already checks for empty descriptions and authentication is performed
on initialization, so it is unlikely that other error happen. If it does,
then they will be added as they appear.
Fixes #25.
=> feat(Github): show error message when PR already exists

src/error/errors.js, src/git/local/index.js
=> fix(git): show an error when there is no key in the agent

src/issue-tracker/jira/status.js
* Split in review and done regex so done doesn't get picked
if there is a review state but done comes first.
Fixes #29.
=> fix(Jira): infer in review state correctly

src/error/errors.js, src/git/local/index.js
Show the proper error if local branch is behind the remote one and it can't be fast forwarded.
Fixes #40.
=> fix(git): handle push errors

README.md, src/config/index.js, src/config/read-config-file.js, src/fotingo-start.js, src/git/util.js, src/issue-tracker/jira/index.js
* fix(config): do not use empty object when updating local config file
* If the config file had info in a different path than the data being updated if was removed.
* Now the issue types are fetched from Jira and stored in the config file with a short name.  There are some defaults to match the existing behavior (feature and story => f, task => c). In any other cases, the first letter of the type is used for the short name.
* Users can define the templates in the config file under jira => templates => branch. For now this is the data passed to those templates: issue.shortName, issue.key and issue.sanitizedSummary. In order to access them from the template, { and } must be used to interpolate.
Fixes #43, #38.
=> feat(start): allow user to define branch name templates

src/git/util.js
These characters are problematic when referencing the branch name in the terminal
=> fix(createBranchName): del < and > from sanitized summary

README.md, src/error/errors.js, src/fotingo-release.js, src/fotingo.js, src/git/github/index.js, src/git/local/index.js, src/issue-tracker/http-client.js, src/issue-tracker/jira/index.js, src/issue-tracker/jira/status.js, src/reporter/index.js, src/util.js
This command will allow to create a release for the issues in the current branch (or extra issues using the `-i` option). The release process is as follows:
```bash
fotingo release -i <issue-id> -i <another-issue-id> <release-id>
```
* Extract the issues from the branch name (skip this with `-n` option)  and commit messages.
* Create release notes from the affected issues data.
* Allow user to edit the release notes.
* Create a jira version with name `<release-id>`. The release is set to released status.
* Set the fix version of the affected issues to `<release-id>`.
* Set the status of the affected issues to *done*.
* Create a github release for the `<release-id>` tag with the release notes.
For now, there must a be a tag named `<release-id>`. Future  versions could create this tag if it …
=> feat: create a release command

src/error/errors.js, src/fotingo-start.js, src/issue-tracker/jira/index.js, src/issue-tracker/jira/status.js, src/issue-tracker/util.js, yarn.lock
**Changes**
* fix(yarn): solve issue with request
* feat(start): add option to create an issue
If the -c option is specified, then it will create a new issue. Start  with `-c` needs to know the project `-p`, the type of issue to create  `-t` and a description of the issue.
Some extra validation rules needed to be added to the start script.
The jira client now has a method to create an issue.
=> feat(start): add option to create an issue

src/commands/Release.ts, src/config.ts, src/enhanceConfig.ts, src/git/Git.ts, src/git/Github.ts, src/git/Remote.ts, src/issue-tracker/Config.ts, src/issue-tracker/Issue.ts, src/issue-tracker/Jira.ts, src/templates/getReleaseNotes.ts, src/types.ts
Extract the release note creation from Jira into its own file.
Ask the user for release notes after the Jira release has been created so we can include the URL in them.
Minor bug fixes
**Changes**
* feat: create a method to get the release notes
* chore(types): define type for release config
* chore(config): move release template into new field in config
* chore(Git): fix compiler warning
* chore(Jira): del no longer existing fields
* refactor(Jira): extract release note creation
* chore(Github): update signature to meet new release notes design
* feat(Release): include jira release on the notes
=> feat: include Jira release URL in release notes

src/issue-tracker/jira/Jira.ts
The wrong RX operator was being used and that meant that not all the issues were getting updated when doing a release.
**Changes**
* fix(Jira): use correct operator when modifying multiple issues
=> fix(Jira): releasing multiple issues doesn't update all of them

README.md
A small change of something I ran into while trying to make a release. The order of the  example command given for releasing doesn't work as currently shown.
For example:
Does NOT work: fotingo release -i SCHU-6070 v0.1.30508 
Does work: fotingo release v0.1.30508 -i SCHU-6070
I updated the example command to match the correct order.
Small update for those who are new to the repo.
{firstIssueSummary}
{fixedIssues}
**Changes**
{changes}
{fotingo.banner}
=> Update README.md - release command section.

package.json, src/git/Github.ts
Sometimes when the cache expires users can get quota exceeded errors. This adds a way to ensure that no parallel call to the Github API is made. It is only applied in certain places, and probably just removing the Promise.all to get the collaborators should fix it, but this gives more flexibility for new features that may need it.
**Changes**
* fix(Github): allow to limit parallel calls
=> fix(Github): throttle calls to avoid quota issues

.github/PULL_REQUEST_TEMPLATE.md, README.md, package.json, src/enhanceConfig.ts, src/git/Github.ts, src/ui/useCmd.ts, yarn.lock
This PR fixes some issues related to Github and the creation of PRs. It improves the logic for creating the default summary and description of the PR. It also escapes HTML content from the PR template (I had commit messages referencing some react components and they wouldn't show up in the description as they are not valid HTML). 
BREAKING CHANGE: In the PR template keys `firstIssue.summary` and `firstIssue.description` are now just `summary` and `description`.
**Changes**
* fix(prTemplate): use correct placeholders
* fix(useCmd): exit thread mode when there is an error
* feat(Github): improve PR summary and description
* chore(enhanceConfig): update default template to use new keys
* docs(readme): update docs for PR template keys
* chore(dependencies): add escape-html
* …
=> fix(Github): several Github minor bug fixes

.github/workflows/auto-merge-prs.yml
Using the empty string prevents multiple dependabot PRs from getting merged
**Changes**
* chore(autoAssign): set label for auto update
=> chore(autoAssign): set label for auto update

.github/workflows/auto-merge-prs.yml, src/git/Github.ts
Increase delay for merge PRs to 60s as it was not enough and fix Github template names, which were mixed.
**Changes**
* chore(autoAssign): increase delay to 60s
* fix(Github): name template keys correctly
=> chore(autoAssign): increase delay to 60s

src/issue-tracker/jira/Jira.ts
This character was not being escaped and was producing some invalid branch names
Fixes #259.
**Changes**
* fix(Jira): ignore ‘ in issue sanitized summary
=> fix(Jira): ignore ‘ in issue sanitized summary

src/git/Github.ts, src/io/cacheable.ts, src/io/debug.ts, src/io/messenger.ts, src/ui/SelectRequest.tsx, test/io/__snapshots__/cacheable.test.ts.snap, test/io/cacheable.test.ts
After having added queues for Github, when the cache expires it takes a long time to get all the data to cache. This PR increases the cache time for most of the GH data and also removes the collabotators as possible reviewers.
It also starts caching Github users globally so they can be resued from repo to repo.
Finally, it also creates a shared debugger and adds some debugging messages for Github as well as a `pause()` method that allows to see output before jumping into things like editing a file in vim.
**Changes**
* feat(cacheable): make TTL optional
* chore(Github): improve caching and remove contributors from reviewers
* chore(cacheable): allow to disable cache via an env var
* chore: create a shared debugger that modules can extend
* fix(SelectRequest): remove …
=> fix(Github): improve caching and add logging

README.md, package.json, src/cli/start.ts, src/commands/Start.ts, src/commands/run.ts, src/io/input.ts, src/issue-tracker/Tracker.ts, src/issue-tracker/jira/Jira.ts, src/issue-tracker/jira/types.ts, src/types.ts, test/issue-tracker/__snapshots__/Jira.test.ts.snap, test/lib/data.ts
This PR introduces the first version (very early stage) of a start cmd where no issue needs to be specified. In that case, the user is prompted with the list of the top 15 issues they are assigned that are in Backlog or selected for development (excluding epics). 
**TODOs**
**Changes**
* chore(Jira): define type for Issue status
* chore(Tracker): add method to interface to get current user issues
* fix(types): use new value that jira returns
* feat(io): allow 0 limit and add allowTextSearch option
* feat(Jira): add methods to get statuses and current user open issues
* feat(start): make issue-id|title optional
* feat(Start): ask user to select an issue if none was specified
* test: update failing tests
=> feat:(start): ask user to select issues if none was specified

src/io/file.ts, src/templates/getReleaseNotes.ts, test/lib/data.ts, test/templates/__snapshots__/getReleaseNotes.test.ts.snap, test/templates/getReleaseNotes.test.ts
This PR fixes the release notes so there is an empty line between the different issue types. Although in rendered md it looks good, it doesn't look good on the text version.
It also fixes an issue with the way `editor` was being imported
Fixes #339
**Changes**
* fix(release-notes): add extra line between issue types
* fix(file): import editor correctly
=> fix(release-notes): add extra line between issue types

.gitignore, bin/run, package.json, src/index.ts, yarn.lock
`oclif-dev` does not work well with `module-alias` and typescript paths (see https://github.com/oclif/oclif/issues/288). `tscpaths` is a cleaner solution that doesn't require loading extra modules when running fotingo.
**Changes**
* chore(deps): remove module-alias
* chore(deps): install tscpaths
* chore: ignore packed package
=> refactor: replace module-alias with tscpaths

src/issue-tracker/jira/Jira.ts, src/issue-tracker/jira/types.ts, test/issue-tracker/Jira.test.ts, test/issue-tracker/__snapshots__/Jira.test.ts.snap, test/lib/data.ts
There was a typo in the regex that prevented characters from being escaped as intended.
Fixes #549
**Changes**
* chore: allow to pass overrides to mocked issue
* test(jira): add failing test for bug
* chore(jira): remove invalid field in JiraIssue
* fix(jira): escape summary characters correctly
=> fix(jira): escape summary characters correctly

src/cli/FotingoCommand.ts, src/commands/start.ts, src/io/messenger.ts, src/ui/Fotingo.tsx, src/ui/props.ts, src/ui/ui.tsx, src/ui/useCmd.ts
When migrating to oclif I forgot to migrate the part that asks for required configs to users. When a new user does `fotingo start` the app was crashing because the required config was not there.
This PR adds that feature along with other small things.
**Changes**
* chore(messenger): return messages subscription
* fix(ui): avoid memory leak
* chore(ui): return ink instance
* chore(ui): allow to not render the footer
* feat: ask for required missing configs on startup
* feat(start): add message indicating that we are fetching open tickets
=> chore(messenger): return messages subscription

README.md, package.json, src/config.ts, src/enhanceConfig.ts, src/issue-tracker/jira/Config.ts, src/issue-tracker/jira/Jira.ts, src/types.ts, test/issue-tracker/Jira.test.ts, test/lib/data.ts, yarn.lock
This config allows to override the default mapping that fotingo uses to map internal issue statuses to the Jira ones.
**Changes**
* chore(config): import correct definition
* chore(scripts): use tsc-watch
* feat(config): add tracker -> status
* chore(jira): remove unused interface
* refactor(jira): use status regexes from config
* chore(config): enhance config with default status regexes
* docs(readme): add docs for new status config
=> feat(config): add tracker -> status

src/cli/FotingoCommand.ts, src/ui/useCmd.ts
This is useful when using fotingo in a CI environment.
Fixes #622
**Changes**
* fix(ui): exit ui passing errors when there are any
* fix: exit with non-zero code when there are errors
=> fix: exit with non-zero code when there are errors

README.md, src/commands/review.ts, src/git/Github.ts, src/git/Remote.ts, src/types.ts
This PR adds support to create draft PRs and to update a draft PR when calling review if one exists (instead of throwing an error).
An error would still be thrown if there is an open PR that is not a draft or if the `-d` option was set.
I just updated the description from fotingo
**Changes**
* feat(review): add support to create draft PRs
* feat(github): update PR if there is a draft already
=> feat(review): add support to create draft PRs

package.json, test/config.test.ts, test/git/Branch.test.ts, test/git/Git.test.ts, test/io/cacheable.test.ts, test/issue-tracker/Jira.test.ts, test/issue-tracker/JiraError.test.ts, test/network/HttpClient.test.ts, test/setupTests.ts, test/templates/getReleaseNotes.test.ts, test/ui/ControlledSelectInput.test.tsx, test/ui/SelectRequest.test.tsx, yarn.lock
Bumps jest to the latest version
**Changes**
* chore(deps-dev): bump jest from 25.4.0 to 26.0.1
* test: update them so they are compatible with jest 26
=> chore(deps-dev): bump jest from 25.4.0 to 26.0.1

package.json, src/cli/FotingoCommand.ts, src/commands/start.ts, src/ui/useCmd.ts, src/util/text.ts
This PR updates the start command so that the issue type option is fuzzy searched so less letters can be used. It also removes the `sub-task` type, as those can't be created via fotingo.
**Changes**
* fix(ui): catch errors that happen before UI starts
* chore: order dev dependencies
* chore(text-utils): make fields optional to allow for str searches
* chore(command): allow command data to be an observable
* feat(start): use fuzzy search to detect issue type
=> fix(ui): catch errors that happen before UI starts

src/commands/release.ts, src/types.ts
Add option `-n` to not create a Github release. This can be useful especially when using `semantic-release-fotingo`.
**Changes**
* feat(release): add option to not create Github release
=> feat(release): add option to not create Github release

src/git/Github.ts
The collaborators API doesn't seem to be working. I really don't know if it is a token issue or what really 
**WORKING**
```
curl \
-H "authorization: token [YOUR_TOKEN_HERE]" \
https://api.github.com/repos/turo/dunlop/contributors\?per_page=1
```
**NOT WORKING**
```
curl \
-H "authorization: token [YOUR_TOKEN_HERE]" \
https://api.github.com/repos/turo/dunlop/collaborators\?per_page=1
```
=> fix(github): use contributors api instead of collaborators

README.md
Readme change
Configuration example does not work, fix by changing `github` to `git`.
=> chore: correct the example for local config file

src/issue-tracker/jira/Jira.ts, src/types.ts, test/git/__snapshots__/Branch.test.ts.snap, test/issue-tracker/Jira.test.ts, test/issue-tracker/__snapshots__/Jira.test.ts.snap, test/lib/data.ts
This commit fixes enables browsing and starting of tickets with the status "selected for development"
The enhanceConfig had a setting where SELECTED_FOR_DEVELOPMENT status regex matches against `todo`, `to do`, and `selected for development`. When executing `fotingo start`, the filter is built up based on tickets which match the statuses provided by that JIRA instance. However, the SELECTED_FOR_DEVELOPMENT config, since it matches statuses with the name of `todo` or `to do` as well as `selected for development`, would query using the wrong status, trying to match `todo` instead of `selected for development`, meaning all the tickets with status `selected for development` would not match the filter.
**Changes**
Update enhanceConfig.ts
{fotingo.banner}
=> Allow viewing "selected for development" tickets

src/issue-tracker/jira/Jira.ts, test/issue-tracker/Jira.test.ts
The `fotingo start` cmd stopped working because the v2 api it was using is now deprecated.
This PR updates the JQL call to use a new client that uses the v3 rest api. I added a TODO to eventually move all the endpoints to v3.
**Changes**
* fix(jira): use rest v3 api for JQL search
=> fix(jira): use rest v3 api for JQL search
